### ISSUE TITLE
build.skill_gems seems to not work 

### ISSUE THREAD

**Issue by Klasyer** [ppoelzl/PathOfBuildingAPI#51]
Hey! while trying to pull the skill gems out of a Pob, it seems that build.skill_gems doesnt work, tried a few builds and all of them return empty 

`import pobapi 

url = "https://pastebin.com/eVVYtPet" 
build = pobapi.from_url(url) 

print(build.skill_gems)  `

**Comment by ppoelzl** [comment]
Hi! Thank you for your report. To be honest, I haven't properly maintained this project for a while since no one showed interest. I'll try to fix this asap, shouldn't take too long.

**Comment by ppoelzl** [comment]
Fixed in version 0.6.0. I also made a new release on PyPI. Stay tuned for more active development from now on! @Klasyer
